services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /path/to/repository:/app/repo  # Mount your code repo HERE
    depends_on:
      - vectorstore

  vectorstore:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
